name: kamusi
description: A new Flutter project.
version: 1.0.1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  anisi_controls:
    git:
      url: https://github.com/jacksiro254/anisi_controls.git
  async: ^2.5.0
  auto_size_text: ^3.0.0-nullsafety.0
  bloc: ^7.1.0
  carousel_slider: ^4.0.0
  card_swiper: ^1.0.4
  dio: ^4.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.2.0
  flutter_custom_clippers: ^2.0.0
  flutter_form_builder: ^6.1.0+1
  flutter_html: ^2.1.2
  flutter_launcher_icons: ^0.9.2
  flutter_local_notifications: ^8.1.1+1
  flutter_sound: ^8.2.5
  flutter_svg: ^0.22.0
  fluttertoast: ^8.0.8
  html_unescape: ^2.0.0
  http: ^0.13.3
  json_annotation: ^4.0.0
  path_provider: ^2.0.1
  provider: ^6.0.0
  pull_to_refresh: ^2.0.0
  purchases_flutter: ^3.4.5
  rxdart: ^0.26.0-nullsafety.1
  share: ^2.0.4
  shared_preferences: ^2.0.7
  simple_animations: ^3.1.1
  sliding_sheet: ^0.3.7
  sqflite: ^2.0.0+3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appicon.png"

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/audio/
    - assets/images/
    - assets/images/help/
