name: kamusi
description: kiswahili kitukuzwe

version: 1.2.7+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animated_floatactionbuttons: ^0.1.0
  async: ^2.5.0
  auto_size_text: ^2.1.0
  bubble_bottom_bar: ^1.2.0
  change_app_package_name: ^0.1.2
  cupertino_icons: ^1.0.2
  firebase_analytics: ^7.1.1
  flutter_custom_clippers: ^1.1.2
  flutter_html: ^1.3.0
  flutter_launcher_icons: ^0.9.0
  flutter_local_notifications: ^8.0.0
  flutter_sound: ^8.2.5
  html_unescape: ^2.0.0
  http: ^0.13.1
  json_annotation: ^4.0.1
  json_serializable: ^4.1.0
  loadmore: ^2.0.0
  page_transition: ^2.0.2
  path_provider: ^2.0.1
  percent_indicator: ^3.0.1
  provider: ^5.0.0
  purchases_flutter: ^3.1.0
  pull_to_refresh: ^1.6.4
  responsive_widgets: ^2.0.1
  simple_animations: ^3.0.3
  share: ^2.0.1
  shared_preferences: ^2.0.5
  sqflite: ^2.0.0+3
  url_launcher: ^6.0.3
  wakelock: ^0.2.1

dev_dependencies:
  flutter_driver:
  #  sdk: flutter
  test: any
  build_runner: ^1.1.2
  debug_mode: ^0.1.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appicon.png"

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/audio/
    - assets/help/
    - assets/images/